[package]
name = "rust-host"
version = "0.1.0"
authors = ["Amit Saha <asaha@atlassian.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

wasm3 = {version = "0.1.3", features = ["build-bindgen"]}
