[package]
name = "hellohost"
version = "0.1.0"
authors = ["Amit Saha <asaha@atlassian.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime-provider = "0.0.2"
wapc = "0.10.1"
load_file = "1.0.0"
